src/app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

Route::filter('guest', function() {
    if (Auth::check()) {
        return redirect()->route('LoggedIn.Home.OnlineInformation');
    }
});

Route::get('/', function () {
    return redirect()->route('Authentication.GetLogin');
});
Route::get('auth/login', function () {
    return redirect()->route('Authentication.GetLogin');
});

Route::group(array(
    'prefix' => 'Authentication',
    'as' => 'Authentication.'
        ), function() {

    Route::get('Login', array(
        'uses' => 'AuthenticationController@GetLogin',
        'as' => 'GetLogin'
    ))->before('guest');
    Route::post('Login', array(
        'uses' => 'AuthenticationController@PostLogin',
        'as' => 'PostLogin'
    ))->before('guest');
});

Route::group(array(
    'middleware' => 'auth',
    'prefix' => '!',
    'namespace' => 'LoggedIn',
    'as' => 'LoggedIn.',
        ), function() {

    /*     * ****************** User profile ******************* */
    Route::group(array(
        'prefix' => 'Home',
        'as' => 'Home.',
            ), function() {

        Route::get('OnlineInformation', array(
            'uses' => 'HomeController@OnlineInformation',
            'as' => 'OnlineInformation',
        ));
        Route::post('UpdateOwnProfilePic', array(
            'uses' => 'HomeController@update_image',
            'as' => 'updateProfile',
        ));

        Route::get('UpdateOwnProfile', array(
            'uses' => 'HomeController@edit',
            'as' => 'updateOwnProfile',
        ));
        Route::post('UpdateOwnProfile', array(
            'uses' => 'HomeController@update',
            'as' => 'updateOwnProfileAction',
        ));

        Route::get('UpdateProfilePassword', array(
		    'uses' => 'HomeController@edit_password',
            'as' => 'updateProfilePassword',
            
        ));
        Route::post('UpdateProfilePassword', array(
		    'uses' => 'HomeController@update_password',
            'as' => 'updatePasswordAction',
            
        ));
		


        Route::get('Logout', array(
            'uses' => 'HomeController@Logout',
            'as' => 'Logout',
        ));
    });



    Route::group(array(
        'prefix' => 'Settings',
        'as' => 'Settings.',
            ), function() {

        Route::get('/', array(
            'uses' => 'SettingsController@Index',
            'as' => 'Index',
        ));

        Route::group(array(
            'namespace' => 'Settings'
                ), function() {

            Route::resource('Teacher', 'TeacherController', array(
                'names' => array(
                    'index' => 'Teacher.Index',
                    'create' => 'Teacher.Create',
                    'store' => 'Teacher.Store',
                    'edit' => 'Teacher.Edit',
                    'update' => 'Teacher.Update',
                    'destroy' => 'Teacher.Delete',
                )
            ));
            Route::resource('Subject', 'SubjectController', array(
                'names' => array(
                    'index' => 'Subject.Index',
                    'create' => 'Subject.Create',
                    'store' => 'Subject.Store',
                    'edit' => 'Subject.Edit',
                    'update' => 'Subject.Update',
                )
            ));


            Route::group(array(
                'prefix' => 'TeacherPrivilege',
                'as' => 'TeacherPrivilege.'
                    ), function() {
                Route::get('GetTeachersByInstituteBranchVersionID/{IbvID}', array(
                    'as' => 'GetTeachersByInstituteBranchVersionID',
                    'uses' => 'TeacherPrivilegeController@GetTeachersByInstituteBranchVersionID',
                ))->where('IbvID', '[0-9]+');
                Route::get('GetAssignedSubjectsByTeacherID/{TeacherID}/{IbvID}', array(
                    'as' => 'GetAssignedSubjectsByTeacherID',
                    'uses' => 'TeacherPrivilegeController@GetAssignedSubjectsByTeacherID',
                ))->where(array(
                    'TeacherID' => '[0-9]+',
                    'IbvID' => '[0-9]+',
                ));
                Route::post('AssignedSubjectsToTeacherID', array(
                    'as' => 'AssignedSubjectsToTeacherID',
                    'uses' => 'TeacherPrivilegeController@AssignedSubjectsToTeacherID',
                ));
                /*  Route::get('GetSectionsByClassIDAndGroupIDAndIbvID/{ClassID}/{GroupID}/{IbvID}', array(
                  'as' => 'GetSectionsByClassIDAndGroupIDAndIbvID',
                  'uses' => 'TeacherPrivilegeController@GetSectionsByClassIDAndGroupIDAndIbvID',
                  ))->where(array(
                  'ClassID' => '[0-9]+',
                  'GroupID' => '[0-9]+',
                  'IbvID' => '[0-9]+',
                  )); */
                Route::get('GetSectionsByClassIDAndGroupIDAndIbvID/{IbvID}/{ClassID}', array(
                    'as' => 'GetSectionsByClassIDAndGroupIDAndIbvID',
                    'uses' => 'TeacherPrivilegeController@GetSectionsByClassIDAndGroupIDAndIbvID',
                ))->where(array(
                    'IbvID' => '[0-9]+',
                    'ClassID' => '[0-9]+',
                ));

                Route::get('GetSubjectsByClassIDAndGroupIDAndIbvID/{ClassID}/{GroupID}/{IbvID}', array(
                    'as' => 'GetSubjectsByClassIDAndGroupIDAndIbvID',
                    'uses' => 'TeacherPrivilegeController@GetSubjectsByClassIDAndGroupIDAndIbvID',
                ))->where(array(
                    'ClassID' => '[0-9]+',
                    'GroupID' => '[0-9]+',
                    'IbvID' => '[0-9]+',
                ));
                Route::post('UpdateStatus', array(
                    'as' => 'UpdateStatus',
                    'uses' => 'TeacherPrivilegeController@UpdateStatus',
                ));
            });




            Route::resource('TeacherPrivilege', 'TeacherPrivilegeController', array(
                'names' => array(
                    'index' => 'TeacherPrivilege.Index',
                    'create' => 'TeacherPrivilege.Create',
                //'store' => 'TeacherPrivilege.Store',
                )
            ));

            Route::group(array(
                'prefix' => 'ClassTeacher',
                'as' => 'ClassTeacher.'
                    ), function() {
                Route::get('GetTeachersByInstituteBranchVersionID/{IbvID}', array(
                    'as' => 'GetTeachersByInstituteBranchVersionID',
                    'uses' => 'ClassTeacherController@GetTeachersByInstituteBranchVersionID',
                ))->where('IbvID', '[0-9]+');
                Route::get('GetAssignedClassTeachersByTeacherID/{TeacherID}/{IbvID}', array(
                    'as' => 'GetAssignedClassTeachersByTeacherID',
                    'uses' => 'ClassTeacherController@GetAssignedClassTeachersByTeacherID',
                ))->where(array(
                    'TeacherID' => '[0-9]+',
                    'IbvID' => '[0-9]+',
                ));
                Route::post('AssignedClassTeachersToTeacherID', array(
                    'as' => 'AssignedClassTeachersToTeacherID',
                    'uses' => 'ClassTeacherController@AssignedClassTeachersToTeacherID',
                ));
                Route::get('GetGroupsByClassIDAndTeacherID/{ClassID}/{TeacherID}', array(
                    'as' => 'GetGroupsByClassIDAndTeacherID',
                    'uses' => 'ClassTeacherController@GetGroupsByClassIDAndTeacherID',
                ))->where(array(
                    'ClassID' => '[0-9]+',
                    'TeacherID' => '[0-9]+',
                ));
                Route::get('GetSectionsByClassIDTeacherIDAndGroupID/{ClassID}/{TeacherID}/{GroupID}', array(
                    'as' => 'GetSectionsByClassIDTeacherIDAndGroupID',
                    'uses' => 'ClassTeacherController@GetSectionsByClassIDTeacherIDAndGroupID',
                ))->where(array(
                    'ClassID' => '[0-9]+',
                    'GroupID' => '[0-9]+',
                    'TeacherID' => '[0-9]+',
                ));
                Route::post('UpdateStatus', array(
                    'as' => 'UpdateStatus',
                    'uses' => 'ClassTeacherController@UpdateStatus',
                ));
            });


            Route::resource('ClassTeacher', 'ClassTeacherController', array(
                'names' => array(
                    'index' => 'ClassTeacher.Index',
                    'create' => 'ClassTeacher.Create',
                //'store' => 'TeacherPrivilege.Store',
                )
            ));
			
			//****** student view*************//

			Route::resource('StudentsView', 'StudentsViewController', array(
                'names' => array(
                    'index'    => 'studentsView.index',
					'edit'     => 'studentsView.edit',
					'update'   => 'studentsView.update',
                )
            ));
			Route::get('StudentsView/{BranchVersionID}/{ClassID}', array(
				 'uses' => 'StudentsViewController@getBranchSection'
			))->where(array(
				'BranchVersionID', '[0-9]+',
				'ClassID', '[0-9]+',
		    ));
			Route::post('StudentsView/View', array(
                'uses' => 'StudentsViewController@view'
            ));
			
			Route::group(array(
                'prefix' => 'StudentViewPrint',
                'as'     => 'studentViewPrint.'
            ), function() {
				Route::get('StudentsView/Print/{branchVersion?}/{class?}/{section?}/{group?}', array(
					'as'   => 'studentPrint',

src/app/Http/Controllers/LoggedIn/HomeController.php
<?php

namespace App\Http\Controllers\LoggedIn;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Auth;
use App\SecUserLogon;
use App\User;
use Validator;
class HomeController extends Controller {
    
    private $ViewPagePath = 'LoggedIn.Home.';

    public function __construct() {
    }

       public function OnlineInformation() {

        $LoggedInUserFullName = Auth::user()->full_name;

        $Data = array();
        $Data['PageTitle'] = 'Welcome ' . $LoggedInUserFullName . ' to your dashboard';

        return view($this->ViewPagePath . 'OnlineInformation', $Data);
    }
	
    /***********************  update picture ************************/
	
    public function update_image(Request $request){

        

        $this->data['Details'] = User::findOrFail( Auth::user()->user_id);

        $profile = User::find( Auth::user()->user_id);
		$MessageType = 'SuccessMessage';
        $Message = 'picture updated successfully.';

        if($request->hasFile('image')) {

            if ($request->file('image')->isValid()) {

                $destinationPath = 'img/ProfilePicture';
                $extension = $request->file('image')->getClientOriginalExtension();
                $fileName = Auth::user()->user_id.'.'.$extension;

                $request->file('image')->move($destinationPath,$fileName);

                $profile->image = $fileName;
                $profile->save();
            }
        }
        return redirect()->route('LoggedIn.Home.OnlineInformation')
            ->with($MessageType, $Message);
    }



	/*************************** edit profile  **********************************/

	  public function edit(Request $request){
		  
		$Data = array();
        $Data['PageTitle'] = 'Update Your Information';
        return view($this->ViewPagePath . 'edit', $Data);	
    }
	/*********************** update profile ******************************/
	
	public function update(Request $request){
		 $this->data['Details'] = User::findOrFail( Auth::user()->user_id);     
        $validator = Validator::make($request->all(), array(
                    'full_name' => 'required|max:255',
                    'email'     => 'required',
                    'phone_no'  => 'required',
        ));
        if ($validator->fails()) {
            return redirect()->route('LoggedIn.Home.updateOwnProfile')
                            ->withErrors($validator)
                            ->withInput();
        }
        $profile = User::find(Auth::user()->user_id);
        $profile->full_name = $request->full_name;
        $profile->email = $request->email;
        $profile->phone_no = $request->phone_no;      
        $profile->save();

	    return redirect()->route('LoggedIn.Home.OnlineInformation')
            ->with('SuccessMessage', 'Profile updated successfully.');					
    }

	
	
	/*******************  update password  *****************************/
	
	public function edit_password(Request $request){        
		 if (!$request->ajax()) {			 
		   $Data = array();
           $Data['PageTitle'] = 'Update Your Password';
		   
            try {
				return view($this->ViewPagePath . 'passwordChange', $Data);
            } catch (\Exception $ex) {
                echo $ex->getMessage();
            }
        } else {
            throw new Exception('Invalid request!');
        }
    }
	  /****************/

	public function update_password(Request $request){
		
		  $this->data['Details'] = User::findOrFail( Auth::user()->user_id);       	
           $validator = Validator::make($request->all(), array(
                    'oldpassword' => 'required',
                    'password'    => 'required',
                    'cnfpassword' => 'required',
           ));
           if ($validator->fails()) {
            return redirect()->route('LoggedIn.Home.updateProfilePassword')
                            ->withErrors($validator)
                            ->withInput();

           }	
 		   
            $MessageType = 'SuccessMessage';
            $Message = 'Password updated successfully.';	
      
			
		   // //// Getting the User  //////////
		   
		   if(!Hash::check($request->oldpassword, Auth::user()->password)){
			   return redirect()->route('LoggedIn.Home.updateProfilePassword')
                            ->with('ErrorMessage', 'Your current password didn\'t match.');
		   }
		   if($request->password != $request->cnfpassword){
			   return redirect()->route('LoggedIn.Home.updateProfilePassword')
                    ->with('ErrorMessage', 'Your new password and confirm password didn\'t match.');
		   }		   		   		
			$user = User::find(Auth::user()->user_id);
			$user->password = bcrypt($request->password);
			$user->save();
			
        return redirect()->route('LoggedIn.Home.OnlineInformation')
                        ->with($MessageType, $Message);

	  }

	

	
/*********************** Logout **************************/

    public function Logout(Request $request) {

//        echo 'getLogout';exit();
        $login_id = $request->session()->get('sessLogonId');
        //echo $login_id;exit();
        try {

            if (!empty($login_id) && (int) $login_id > 0 && Auth::check()) {

                //$login_id = $request->session()->get('sess_login_id');
                $logout = SecUserLogon::find($login_id);
                $logout->logout_time = date('Y-m-d H:i:s');
                $logout->save();

                $request->session()->flush();

                Auth::logout();

                return redirect()->route('Authentication.GetLogin')->with('SuccessMessage', 'You have successfully logged out.');
            }else{
                throw new Exception('Invalid Request!');
            }
        } catch (\Exception $ex) {
            //return redirect()->route('getLogin');
            echo $ex->getMessage();
        }
    }

}

src/app/Http/Controllers/LoggedIn/SettingsController.php
<?php

namespace App\Http\Controllers\LoggedIn;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Auth;
use DB;

class SettingsController extends Controller {
    
    private $ViewPagePath = 'LoggedIn.Settings.';
    private $MenuID = 32;

    public function __construct() {
    }

    public function Index() {

        $Data = array();
        $Data['PageTitle'] = 'Settings';
        
        $Data['ChildMenus'] = DB::select('call get_child_menu_list("' . $this->MenuID . '")');
        //echo '<pre>';print_r($Data['ChildMenus']);echo '</pre>';exit();
        if(!empty($Data['ChildMenus'])){
            return view($this->ViewPagePath . 'Index', $Data);
        }else{
            throw new \Exception('Invalid Request!');
        }

        
    }

}

src/resources/views/LoggedIn/Home/OnlineInformation.blade.php
@extends('Layouts.Application')
<?php
//echo '<pre>';print_r($data);echo '</pre>';exit();
?>

@section('MainContent')


<div class="row">
    <div class="col-sm-12">
     
        <div class="panel panel-default">
		@include('Layouts.FormValidationErrors')
                @include('Layouts.ErrorSuccessAndWarninMessages')
            <div class="panel-heading" style="text-align: center"><h3> Online Information </h3></div>
            <div class="panel-body">

             	 <div class="media">
				  <div class="media-left">
					
					  <img class="img-circle" src="{{ asset('img/ProfilePicture') . '/' . Auth::user()->image }}"
                           alt="{{ Auth::user()->image }}" class="img-responsive" width="200" height="150"/>
					
					<b><a href="#" data-toggle="modal" data-target="#myModal"> Edit Picture </a></b>
				  </div>
				  <div class="media-body">
					<h4 class="media-heading">{{Auth::user()->full_name}}</h4>
								
						<!--<form class="form-horizontal">-->
						  
							<div class="form-group">
							
								<label for="email" class="col-sm-4 control-label">E-mail </label>
								<div class="col-sm-6">
								   <p class="form-control-static">{{Auth::user()->email}}</p>
								</div>
								<label for="username" class="col-sm-4 control-label">Username </label>
								<div class="col-sm-6">
								  <p class="form-control-static">{{Auth::user()->username}}</p>
								</div>
							
								<label for="email" class="col-sm-4 control-label">Phone No.  </label>
								<div class="col-sm-6">
								  <p class="form-control-static">{{Auth::user()->phone_no}}</p> 
								</div>		
                                <label for="email" class="col-sm-4 control-label">Phone No.  </label>
								<div class="col-sm-6">
								  <p class="form-control-static">{{Auth::user()->phone_no}}</p> 
								</div>
								
							</div>
							<div class="form-group">
								<div class="col-sm-10">
								  <a href="{{ url(route('LoggedIn.Home.updateOwnProfile')) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Update Profile</a>&nbsp;&nbsp;	  
								  <a href="{{ url(route('LoggedIn.Home.updateProfilePassword')) }}" class="btn btn-primary btn-sm"><i class="fa fa-key"></i> Change Password</a>  
								</div>
							</div>
							
						
					   <!--</form>-->											
				  </div>
				</div>

        </div>

   

</div>	
</div>
</div>
<!-- Modal content-->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"> Change Your Profile Picture </h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal" role="form" method="POST" action="{{url(route('LoggedIn.Home.updateProfile'))}}" enctype="multipart/form-data">
                    {{ csrf_field() }}

                  <div class="form-group form-group-sm">
                        <label for="image" class="col-sm-3 control-label">Select image </label>
                        <div class="col-sm-6">
                             <input type="file" name="image" id="image" value="{{ old('image') }}" />
                        </div>
                        @if ($errors->has('image'))
                        <span class="help-block">
                            <strong class="text-danger">{{ $errors->first('image') }}</strong>
                        </span>
                        @endif
                    </div>

                    <div class="form-group form-group-sm">
                        <div class="col-sm-offset-3 col-sm-10">
                            <button type="submit" class="btn btn-success btn-sm">
                                <i class="fa fa-floppy-o" aria-hidden="true"></i>
                                Save
                            </button>
                        </div>
                    </div>
                </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
   </div>
  </div>

@endsection

src/resources/views/LoggedIn/Home/edit.blade.php
@extends('Layouts.Application')

@section('MainContent')

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><strong> Update Your Profile</strong></div>
            <div class="panel-body">
                 @include('Layouts.FormValidationErrors')
                 @include('Layouts.ErrorSuccessAndWarninMessages')
               

                <form class="form-horizontal" role="form" method="POST" action="{{ url(route('LoggedIn.Home.updateOwnProfileAction')) }}">
                    {{ csrf_field() }}

                    <div class="form-group form-group-sm">
                        <label for="full_name" class="col-sm-2 control-label">Full Name <sup><i class="fa fa-asterisk"style="color:red"></i></sup></label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="full_name" name="full_name" value="{{Auth::user()->full_name}}">
                        </div>
                      
                    </div>
					 <div class="form-group form-group-sm">
                        <label for="email" class="col-sm-2 control-label">E-mail <sup><i class="fa fa-asterisk"style="color:red"></i></sup></label>
                        <div class="col-sm-6">
                            <input type="email" class="form-control" id="email" name="email"  value="{{ Auth::user()->email }}">
                        </div>
                      
                    </div>
					
					
					 <div class="form-group form-group-sm">
                        <label for="phone_no" class="col-sm-2 control-label">Phone No  <sup><i class="fa fa-asterisk"style="color:red"></i></sup></label>
                        <div class="col-sm-6">                                                        
                            <input type="text" class="form-control" id="phone_no" name="phone_no"  value="{{ Auth::user()->phone_no }}">
                        </div>
                       
                    </div>
					 
       

                    <div class="form-group form-group-sm">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success btn-sm">
                                <i class="fa fa-floppy-o" aria-hidden="true"></i>
                                Save
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

src/resources/views/LoggedIn/Home/passwordChange.blade.php
@extends('Layouts.Application')

@section('MainContent')


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><strong> Change Your Password</strong></div>
            <div class="panel-body">
             @include('Layouts.FormValidationErrors')
                 @include('Layouts.ErrorSuccessAndWarninMessages')
                <form class="form-horizontal" role="form" method="POST" action="{{ url(route('LoggedIn.Home.updatePasswordAction')) }}">
                    {{ csrf_field() }}

                    <div class="form-group form-group-sm">
                        <label for="oldpassword" class="col-sm-3 control-label">Current  Password <sup><i class="fa fa-asterisk"style="color:red"></i></sup></label>
                        <div class="col-sm-5">
                            <input type="password" class="form-control" id="oldpassword" name="oldpassword" Placeholder="Current  Password"/>
                        </div>
                       
                    </div>
					<div class="form-group form-group-sm">
                        <label for="password" class="col-sm-3 control-label">New Password <sup><i class="fa fa-asterisk" style="color:red"></i></sup></label>
                        <div class="col-sm-5">
                            <input type="password" class="form-control" id="password" name="password" Placeholder="New Password"/>
                        </div>
                      
                    </div>
					<div class="form-group form-group-sm">
                        <label for="cnfpassword" class="col-sm-3 control-label">Conform Password <sup><i class="fa fa-asterisk" style="color:red"></i></sup></label>
                        <div class="col-sm-5">
                            <input type="password" class="form-control" id="cnfpassword" name="cnfpassword" Placeholder="Conform Password"/>
                        </div>
                      
                    </div>
					 
					 
       

                    <div class="form-group form-group-sm">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success btn-sm">
                                <i class="fa fa-floppy-o" aria-hidden="true"></i>
                                Save
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection